name: movie_addict
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  http: ^1.3.0
  provider: ^6.1.2
  intl: ^0.20.2
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
