default_platform(:android)

platform :android do
  desc "Deploy internal test to Play Store"
  lane :deploy_internal do
    gradle(task: "bundleRelease") # Build AAB
    upload_to_play_store(
      track: "internal",
      aab: "../build/outputs/bundle/release/app-release.aab",
      json_key: "fastlane/google_play_api.json",
      version_name: "MovieAddict",
      release_status: "draft",
    )
  end
end
