name: Deploy Flutter App to Play Store (Internal Test)

on:
  push:
    branches:
      - cicd-setup

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Setup Flutter
    #   uses: subosito/flutter-action@v2
    #   with:
    #     flutter-version: 3.x  # Change to your Flutter version

    # - name: Install dependencies
    #   run: flutter pub get

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

    - name: Set up Gradle properties
      run: |
        echo "storeFile=keystore.jks" >> android/key.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

    # - name: Build AAB
    #   run: flutter build appbundle --release

    # - name: Set up google play api
    #   run: echo "${{ secrets.GOOGLE_PLAY_KEY }}" | base64 --decode > android/fastlane/google_play_api.json

    # - name: Deploy to Play Store Internal Testing
    #   run: |
    #     cd android
    #     fastlane deploy_internal

    # - name: Build APK release
    #   run: flutter build apk --release
    
    # - name: Set up firebase service account
    #   run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > android/fastlane/firebase_service_account.json

    # - name: Setup Ruby and Bundler
    #   run: |
    #     sudo apt-get install -y ruby-full
    #     gem install bundler
    #     cd android && bundle install

    - name: Install Fastlane Plugins
      run: |
        cd android
        fastlane add_plugin firebase_app_distribution

    # - name: Deploy to Firebase App Distribution
    #   run: |
    #     cd android
    #     fastlane deploy_firebase
    #   env:
    #     FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}