name: Deploy Flutter Apps

on:
  push:
    branches:
      - release/playstore
      - '*'

jobs:
  deploy_internal:
    if: github.ref == 'refs/heads/release/playstore'
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.x

    - name: Install dependencies
      run: flutter pub get

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

    - name: Set up Gradle properties
      run: |
        echo "storeFile=keystore.jks" >> android/key.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

    - name: Build AAB
      run: flutter build appbundle --release

    - name: Set up google play api
      run: echo "${{ secrets.GOOGLE_PLAY_KEY }}" | base64 --decode > android/fastlane/google_play_api.json

    - name: Deploy to Play Store Internal Testing
      run: |
        cd android
        fastlane deploy_internal

  deploy_appdistribution:
    if: ${{ github.ref != 'refs/heads/release/playstore' && startsWith(github.event.head_commit.message, 'ticket-') }}
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.x

    - name: Install dependencies
      run: flutter pub get

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

    - name: Set up Gradle properties
      run: |
        echo "storeFile=keystore.jks" >> android/key.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

    - name: Build APK release
      run: flutter build apk --release
    
    - name: Set up firebase service account
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > android/fastlane/firebase_service_account.json

    - name: Setup Ruby and Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install Fastlane
      run: gem install fastlane

    - name: Deploy to Firebase App Distribution
      run: |
        cd android
        fastlane deploy_firebase
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}