name: Deploy Flutter App to Play Store (Internal Test)

on:
  push:
    branches:
      - cicd-setup

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Ensure correct permissions
      run: chmod +x android/gradlew

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.x  # Change to your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

    - name: Set up Gradle properties
      run: |
        echo "storeFile=keystore.jks" >> android/key.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

    - name: Build AAB
      run: flutter build appbundle --release --build-dir=build

    - name: Set up Fastlane
      run: echo "${{ secrets.GOOGLE_PLAY_KEY }}" | base64 --decode > android/fastlane/google_play_api.json

    - name: Deploy to Play Store Internal Testing
      run: |
        cd android
        fastlane deploy_internal
      env:
        GOOGLE_PLAY_KEY: ${{ secrets.GOOGLE_PLAY_KEY }}
